"""add RSI

Revision ID: 4419b5720797
Revises: 4ad194aab021
Create Date: 2022-09-28 13:43:53.295435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4419b5720797'
down_revision = '4ad194aab021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=20), nullable=False),
    sa.Column('site_name', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Integer(), nullable=False),
    sa.Column('addr1_og', sa.String(length=30), nullable=True),
    sa.Column('addr2_og', sa.String(length=30), nullable=True),
    sa.Column('addr3_og', sa.String(length=30), nullable=True),
    sa.Column('zone_og', sa.Integer(), nullable=False),
    sa.Column('addr1_dn', sa.String(length=30), nullable=True),
    sa.Column('addr2_dn', sa.String(length=30), nullable=True),
    sa.Column('addr3_dn', sa.String(length=30), nullable=True),
    sa.Column('zone_dn', sa.Integer(), nullable=False),
    sa.Column('trip_purpose', sa.Integer(), nullable=False),
    sa.Column('passenger12', sa.Integer(), nullable=True),
    sa.Column('passenger34', sa.Integer(), nullable=True),
    sa.Column('passenger58', sa.Integer(), nullable=True),
    sa.Column('cargo_type', sa.Integer(), nullable=True),
    sa.Column('cargo_weight', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('crated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsi')
    # ### end Alembic commands ###
