"""add surveyor_name

Revision ID: 7acafe0a58f3
Revises: 4419b5720797
Create Date: 2022-09-28 14:47:49.514380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acafe0a58f3'
down_revision = '4419b5720797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsi', sa.Column('surveyor_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsi', 'surveyor_name')
    # ### end Alembic commands ###
